<a href="https://colab.research.google.com/github/p4arth/NLP/blob/main/ImplementingWordEmbedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
voc_size = 10000

In [4]:
one_repr = [one_hot(words,voc_size) for words in sent]
print(one_repr)

[[2176, 1819, 1566, 4433], [2176, 1819, 1566, 8052], [2176, 6295, 1566, 5235], [6973, 4036, 7786, 6014, 6366], [6973, 4036, 7786, 6014, 2570], [3758, 2176, 3489, 1566, 7144], [2205, 2799, 5059, 6014]]


In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length = 8
embedded = pad_sequences(one_repr, padding='pre', maxlen=sent_length)
print(embedded)

[[   0    0    0    0 2176 1819 1566 4433]
 [   0    0    0    0 2176 1819 1566 8052]
 [   0    0    0    0 2176 6295 1566 5235]
 [   0    0    0 6973 4036 7786 6014 6366]
 [   0    0    0 6973 4036 7786 6014 2570]
 [   0    0    0 3758 2176 3489 1566 7144]
 [   0    0    0    0 2205 2799 5059 6014]]


In [8]:
dim=15

In [9]:
model = Sequential()
model.add(Embedding(voc_size, 15,input_length=sent_length))
model.compile('adam', 'mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 15)             150000    
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(model.predict(embedded))

[[[ 0.03722653  0.00435934  0.01199856  0.0418565   0.01053367
   -0.03696998 -0.03136523  0.04343892 -0.03606521 -0.03202478
    0.0014804   0.03082803  0.02739446  0.01779935 -0.01636821]
  [ 0.03722653  0.00435934  0.01199856  0.0418565   0.01053367
   -0.03696998 -0.03136523  0.04343892 -0.03606521 -0.03202478
    0.0014804   0.03082803  0.02739446  0.01779935 -0.01636821]
  [ 0.03722653  0.00435934  0.01199856  0.0418565   0.01053367
   -0.03696998 -0.03136523  0.04343892 -0.03606521 -0.03202478
    0.0014804   0.03082803  0.02739446  0.01779935 -0.01636821]
  [ 0.03722653  0.00435934  0.01199856  0.0418565   0.01053367
   -0.03696998 -0.03136523  0.04343892 -0.03606521 -0.03202478
    0.0014804   0.03082803  0.02739446  0.01779935 -0.01636821]
  [ 0.01005464 -0.04753747  0.03223139 -0.04942418 -0.01397338
   -0.03831498  0.02304396  0.0118489   0.04229588 -0.02861902
    0.04733744  0.01142605  0.00178071  0.0260492  -0.04632647]
  [-0.03567634 -0.00146068  0.02535459 -0.00848931